module.exports = [
  { name: 'totalAgents', description: 'Total de agentes', endpoint: '/analytics/agents/total' },
  { name: 'ageDistribution', description: 'Distribución de edades de agentes', endpoint: '/analytics/agents/age-distribution' },
  { name: 'ageByFunction', description: 'Edad promedio por función', endpoint: '/analytics/agents/age-by-function' },
  { name: 'agentsByFunction', description: 'Cantidad de agentes por función', endpoint: '/analytics/agents/by-function' },
  { name: 'agentsByEmploymentType', description: 'Agentes por tipo de contratación', endpoint: '/analytics/agents/by-employment-type' },
  { name: 'agentsByDependency', description: 'Agentes por dependencia', endpoint: '/analytics/agents/by-dependency' },
  { name: 'agentsBySecretaria', description: 'Agentes por secretaría', endpoint: '/analytics/agents/by-secretaria' },
  { name: 'agentsBySubsecretaria', description: 'Agentes por subsecretaría', endpoint: '/analytics/agents/by-subsecretaria' },
  { name: 'agentsByDireccionGeneral', description: 'Agentes por dirección general', endpoint: '/analytics/agents/by-direccion-general' },
  { name: 'agentsByDireccion', description: 'Agentes por dirección', endpoint: '/analytics/agents/by-direccion' },
  { name: 'agentsByDepartamento', description: 'Agentes por departamento', endpoint: '/analytics/agents/by-departamento' },
  { name: 'agentsByDivision', description: 'Agentes por división', endpoint: '/analytics/agents/by-division' },
  { name: 'agentsBySeniority', description: 'Agentes por rangos de antigüedad', endpoint: '/analytics/agents/seniority' },
  { name: 'agentsBySecondaryStudies', description: 'Agentes por estudios secundarios', endpoint: '/analytics/agents/secondary-studies' },
  { name: 'agentsByTertiaryStudies', description: 'Agentes por estudios terciarios', endpoint: '/analytics/agents/tertiary-studies' },
  { name: 'agentsByUniversityStudies', description: 'Agentes por estudios universitarios', endpoint: '/analytics/agents/university-studies' },
  { name: 'agentsByTopSecretariasUniversity', description: 'Top secretarías con títulos universitarios', endpoint: '/analytics/agents/top-secretarias-university' },
  { name: 'agentsByTopSecretariasTertiary', description: 'Top secretarías con títulos terciarios', endpoint: '/analytics/agents/top-secretarias-tertiary' },
  { name: 'certificationsRegistrationType', description: 'Agentes por tipo de registración', endpoint: '/analytics/certifications/registration-type' },
  { name: 'certificationsEntryTime', description: 'Agentes por horario de entrada', endpoint: '/analytics/certifications/entry-time' },
  { name: 'certificationsExitTime', description: 'Agentes por horario de salida', endpoint: '/analytics/certifications/exit-time' },
  { name: 'certificationsTopUnits', description: 'Top unidades de registración', endpoint: '/analytics/certifications/top-units' }
];
