module.exports = [
  { name: 'totalAgents', description: 'Total de agentes', endpoint: '/analytics/agents/total' },
  { name: 'ageDistribution', description: 'Distribucion de edades de agentes', endpoint: '/analytics/agents/age-distribution' },
  { name: 'ageByFunction', description: 'Edad promedio por funcion', endpoint: '/analytics/agents/age-by-function' },
  { name: 'ageBySecretaria', description: 'Distribucion de edades por area', endpoint: '/analytics/agents/age-by-secretaria' },
  { name: 'agentsByFunction', description: 'Cantidad de agentes por funcion', endpoint: '/analytics/agents/by-function' },
  { name: 'agentsByEmploymentType', description: 'Agentes por tipo de contratacion', endpoint: '/analytics/agents/by-employment-type' },
  { name: 'agentsByDependency', description: 'Agentes por dependencia', endpoint: '/analytics/agents/by-dependency' },
  { name: 'agentsBySecretaria', description: 'Agentes por secretaria', endpoint: '/analytics/agents/by-secretaria' },
  { name: 'agentsBySubsecretaria', description: 'Agentes por subsecretaria', endpoint: '/analytics/agents/by-subsecretaria' },
  { name: 'agentsByDireccionGeneral', description: 'Agentes por direccion general', endpoint: '/analytics/agents/by-direccion-general' },
  { name: 'agentsByDireccion', description: 'Agentes por direccion', endpoint: '/analytics/agents/by-direccion' },
  { name: 'agentsByDepartamento', description: 'Agentes por departamento', endpoint: '/analytics/agents/by-departamento' },
  { name: 'agentsByDivision', description: 'Agentes por division', endpoint: '/analytics/agents/by-division' },
  { name: 'agentsBySeniority', description: 'Agentes por rangos de antiguedad', endpoint: '/analytics/agents/seniority' },
  { name: 'agentsBySecondaryStudies', description: 'Agentes por estudios secundarios', endpoint: '/analytics/agents/secondary-studies' },
  { name: 'agentsByTertiaryStudies', description: 'Agentes por estudios terciarios', endpoint: '/analytics/agents/tertiary-studies' },
  { name: 'agentsByUniversityStudies', description: 'Agentes por estudios universitarios', endpoint: '/analytics/agents/university-studies' },
  { name: 'agentsByTopSecretariasUniversity', description: 'Top secretarias con titulos universitarios', endpoint: '/analytics/agents/top-secretarias-university' },
  { name: 'agentsByTopSecretariasTertiary', description: 'Top secretarias con titulos terciarios', endpoint: '/analytics/agents/top-secretarias-tertiary' },
  { name: 'certificationsRegistrationType', description: 'Agentes por tipo de registracion', endpoint: '/analytics/certifications/registration-type' },
  { name: 'certificationsEntryTime', description: 'Agentes por horario de entrada', endpoint: '/analytics/certifications/entry-time' },
  { name: 'certificationsEntryTimeByUnit', description: 'Agentes por horario de entrada y unidad', endpoint: '/analytics/certifications/entry-time-by-unit' },
  { name: 'certificationsExitTimeByUnit', description: 'Agentes por horario de salida y unidad', endpoint: '/analytics/certifications/exit-time-by-unit' },
  { name: 'certificationsExitTime', description: 'Agentes por horario de salida', endpoint: '/analytics/certifications/exit-time' },
  { name: 'certificationsTopUnits', description: 'Top unidades de registracion', endpoint: '/analytics/certifications/top-units' },
  { name: 'expedientesTopInitiators', description: 'Top iniciadores de expedientes', endpoint: '/analytics/expedientes/top-initiators' },
  { name: 'expedientesByTramite', description: 'Expedientes por tipo de tramite', endpoint: '/analytics/expedientes/by-tramite' },
  { name: 'expedientesHeatmapTramiteEstado', description: 'Heatmap Tramite x Estado (Expedientes)', endpoint: '/analytics/expedientes/heatmap-tramite-estado' },
  { name: 'expedientesHeatmapIniciadorEstado', description: 'Heatmap Iniciador x Estado (Expedientes)', endpoint: '/analytics/expedientes/heatmap-iniciador-estado' },
  { name: 'sacViaCaptacion', description: 'SAC via de captacion', endpoint: '/analytics/sac/via-captacion' },
  { name: 'sacCierreProblemasTopReclamos', description: 'SAC cierre de problemas - top reclamos', endpoint: '/analytics/sac/cierre-problemas/top-reclamos' },
  { name: 'sacCierreProblemasTopPromedios', description: 'SAC cierre de problemas - top promedios', endpoint: '/analytics/sac/cierre-problemas/top-promedios' },
  { name: 'sacCierreProblemasTopPendientes', description: 'SAC cierre de problemas - top pendientes', endpoint: '/analytics/sac/cierre-problemas/top-pendientes' },
  { name: 'sacCierreProblemasTopCerrados', description: 'SAC cierre de problemas - top cerrados', endpoint: '/analytics/sac/cierre-problemas/top-cerrados' },
  { name: 'sacBocaReceptoraTop', description: 'SAC boca receptora - top cantidad', endpoint: '/analytics/sac/boca-receptora/top' },
  { name: 'sacFrecuenciaTiposCierre', description: 'SAC frecuencia de tipos de cierre', endpoint: '/analytics/sac/frecuencia-tipos-cierre' },
  { name: 'sacTemasTopRecibidos', description: 'SAC temas - top recibidos', endpoint: '/analytics/sac/temas/top-recibidos' },
  { name: 'sacTemasTopVisualizados', description: 'SAC temas - top visualizados', endpoint: '/analytics/sac/temas/top-visualizados' },
  { name: 'sacTemasTopPendientes', description: 'SAC temas - top pendientes', endpoint: '/analytics/sac/temas/top-pendientes' },
  { name: 'sacTemasTopProceso', description: 'SAC temas - top en proceso', endpoint: '/analytics/sac/temas/top-proceso' },
  { name: 'sacTemasTopCerrados', description: 'SAC temas - top cerrados', endpoint: '/analytics/sac/temas/top-cerrados' },
  { name: 'sacTipoContactoTopRecibidos', description: 'SAC tipo de contacto - top recibidos', endpoint: '/analytics/sac/tipo-contacto/top-recibidos' },
  { name: 'sacTipoContactoTopCerrados', description: 'SAC tipo de contacto - top cerrados', endpoint: '/analytics/sac/tipo-contacto/top-cerrados' },
  { name: 'sacLlamadasBarrioTop', description: 'SAC llamadas por barrio - top realizadas', endpoint: '/analytics/sac/llamadas-barrio/top' },
  { name: 'sacAmbienteTopReclamos', description: 'SAC ambiente - top reclamos', endpoint: '/analytics/sac/secretaria-ambiente/top-reclamos' },
  { name: 'sacAmbienteTopPromedios', description: 'SAC ambiente - top promedios', endpoint: '/analytics/sac/secretaria-ambiente/top-promedios' },
  { name: 'sacAmbienteTopPendientes', description: 'SAC ambiente - top pendientes', endpoint: '/analytics/sac/secretaria-ambiente/top-pendientes' },
  { name: 'sacAmbienteTopCerrados', description: 'SAC ambiente - top cerrados', endpoint: '/analytics/sac/secretaria-ambiente/top-cerrados' },
  { name: 'sacInfraestructuraTopReclamos', description: 'SAC infraestructura - top reclamos', endpoint: '/analytics/sac/secretaria-infraestructura/top-reclamos' },
  { name: 'sacInfraestructuraTopPromedios', description: 'SAC infraestructura - top promedios', endpoint: '/analytics/sac/secretaria-infraestructura/top-promedios' },
  { name: 'sacInfraestructuraTopPendientes', description: 'SAC infraestructura - top pendientes', endpoint: '/analytics/sac/secretaria-infraestructura/top-pendientes' },
  { name: 'sacInfraestructuraTopCerrados', description: 'SAC infraestructura - top cerrados', endpoint: '/analytics/sac/secretaria-infraestructura/top-cerrados' },
  { name: 'sacCoordTerritorialTopReclamos', description: 'SAC coordinacion territorial - top reclamos', endpoint: '/analytics/sac/coordinacion-territorial/top-reclamos' },
  { name: 'sacCoordTerritorialTopPromedio', description: 'SAC coordinacion territorial - top promedios', endpoint: '/analytics/sac/coordinacion-territorial/top-promedios' },
  { name: 'sacCoordTerritorialTopPendientes', description: 'SAC coordinacion territorial - top pendientes', endpoint: '/analytics/sac/coordinacion-territorial/top-pendientes' },
  { name: 'sacCoordTerritorialTopCerrados', description: 'SAC coordinacion territorial - top cerrados', endpoint: '/analytics/sac/coordinacion-territorial/top-cerrados' },
];
