import {
  Group as GroupIcon,
  Cake as CakeIcon,
  Schema as SchemaIcon,
  Summarize as SummarizeIcon,
  History as HistoryIcon,
  Assignment as AssignmentIcon,
  Percent as PercentIcon,
  AttachMoney as AttachMoneyIcon,
  Assessment as AssessmentIcon,
  Search as SearchIcon,
  Edit as EditIcon,
  Delete as DeleteIcon,
  ExpandMore as ExpandMoreIcon,
  FilterList as FilterIcon,
  Clear as ClearIcon,
  KeyboardArrowDownRounded as KeyboardArrowDownRoundedIcon,
  CheckRounded as CheckRoundedIcon,
  InfoOutlined as InfoOutlinedIcon,
  Business as BusinessIcon,
  AccountTree as AccountTreeIcon,
  Warning as WarningIcon,
  CheckCircle as CheckCircleIcon,
  Error as ErrorIcon,
  HelpOutline as HelpOutlineIcon,
  ArrowCircleRightOutlined as ArrowCircleRightOutlinedIcon,
  ChevronRight as ChevronRightIcon,
  Brightness4 as Brightness4Icon,
  Brightness7 as Brightness7Icon,
  Download as DownloadIcon,
  PictureAsPdf as PdfIcon,
  TableChart as ExcelIcon,
  Code as JsonIcon,
  Image as ImageIcon,
  MoreVert as MoreVertIcon,
  Settings as SettingsIcon,
  Close as CloseIcon,
  Home as HomeIcon,
  DashboardCustomize as DashboardCustomizeIcon,
  Analytics as AnalyticsIcon,
  AdminPanelSettings as AdminPanelSettingsIcon,
  Logout as LogoutIcon,
  Person as PersonIcon,
  CloudUpload as CloudUploadIcon,
  InsertDriveFile as InsertDriveFileIcon,
  Refresh as RefreshIcon,
  BugReport as BugReportIcon,
  Notifications as NotificationsIcon,
  NotificationsActive as NotificationsActiveIcon,
  Upload as UploadIcon,
  Info as InfoIcon,
  Email as EmailIcon,
  Lock as LockIcon,
  AccountCircle as AccountCircleIcon,
  Add as AddIcon,
  Tune as TuneIcon,
  Description as DescriptionIcon,
  Functions as FunctionsIcon,
  Folder as FolderIcon,
  Layers as LayersIcon,
  Timelapse as TimelapseIcon,
  Tag as TagIcon,
  Login as LoginIcon,
  Security as SecurityIcon,
} from "@mui/icons-material";

const icons = {
  personas: GroupIcon,
  edad: CakeIcon,
  distribucion: SchemaIcon,
  resumen: SummarizeIcon,
  antiguedad: HistoryIcon,
  contratos: AssignmentIcon,
  porcentaje: PercentIcon,
  money: AttachMoneyIcon,
  eficiencia: AssessmentIcon,
  buscar: SearchIcon,
  editar: EditIcon,
  eliminar: DeleteIcon,
  expandir: ExpandMoreIcon,
  filtro: FilterIcon,
  limpiar: ClearIcon,
  flechaAbajo: KeyboardArrowDownRoundedIcon,
  check: CheckRoundedIcon,
  infoOutlined: InfoOutlinedIcon,
  empresa: BusinessIcon,
  organigrama: AccountTreeIcon,
  advertencia: WarningIcon,
  exito: CheckCircleIcon,
  error: ErrorIcon,
  ayuda: HelpOutlineIcon,
  flechaDerecha: ArrowCircleRightOutlinedIcon,
  chevronDerecha: ChevronRightIcon,
  luna: Brightness4Icon,
  sol: Brightness7Icon,
  descargar: DownloadIcon,
  pdf: PdfIcon,
  excel: ExcelIcon,
  json: JsonIcon,
  imagen: ImageIcon,
  opciones: MoreVertIcon,
  configuracion: SettingsIcon,
  cerrar: CloseIcon,
  inicio: HomeIcon,
  herramientas: DashboardCustomizeIcon,
  analitica: AnalyticsIcon,
  admin: AdminPanelSettingsIcon,
  salir: LogoutIcon,
  persona: PersonIcon,
  subir: CloudUploadIcon,
  archivo: InsertDriveFileIcon,
  refrescar: RefreshIcon,
  bug: BugReportIcon,
  campana: NotificationsIcon,
  campanaActiva: NotificationsActiveIcon,
  upload: UploadIcon,
  info: InfoIcon,
  correo: EmailIcon,
  candado: LockIcon,
  cuenta: AccountCircleIcon,
  agregar: AddIcon,
  ajustes: TuneIcon,
  descripcion: DescriptionIcon,
  funciones: FunctionsIcon,
  carpeta: FolderIcon,
  capas: LayersIcon,
  tiempo: TimelapseIcon,
  etiqueta: TagIcon,
  login: LoginIcon,
  seguridad: SecurityIcon,
};

export default icons;
